site_name: Dashboard salute
site_url: https://michelefalcomer.github.io/
theme: 
    name: material


nav:
    - Home: Index.md
    - Dashboard: Dashboard.md
    - Guida: Guida.md
    - Classifica: Classifica.md
    - Report: Report.md

